version: '3.8'

services:
  app:
    container_name: my_app
    image: python:3.8
    command: python /app/main.py
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    container_name: my_db
    image: tiangolo/sqlite:latest
    volumes:
      - db_data:/var/lib/sqlite

volumes:
  db_data:
