services:

  web:
    container_name: web
    restart: always
    build: .
    command: [ "sh", "-c", "sleep 2 && python manage.py runserver 0.0.0.0:8000" ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"

