services:

  django:
    container_name: django
    restart: always
    build: .
#    command: [ "sh", "-c", "sleep 2 && python manage.py runserver 0.0.0.0:8000" ]
#    command: [ "sh", "-c", "gunicorn --bind 0.0.0.0:8000 cleanhouse.wsgi" ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./staticfiles/:/app/staticfiles/
      - /etc/letsencrypt:/etc/letsencrypt/
      - ./well-known/:/app/.well-known/
      - ./media/:/app/media/

