services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 111
      MYSQL_DATABASE: cleaning
      MYSQL_USER: svs
      MYSQL_PASSWORD: 111
    volumes:
      - mysql_data:/var/lib/mysql

#  phpmyadmin:
#    container_name: phpmyadmin
#    image: phpmyadmin:latest
#    restart: always
#    environment:
#      PMA_HOST: mysql
#      MYSQL_ROOT_USER: svs
#      MYSQL_ROOT_PASSWORD: 111
#    ports:
#      - "8080:80"
#    depends_on:
#      - mysql
#
#  web:
#    container_name: web
#    restart: always
#    build: .
#    command: [ "sh", "-c", "sleep 2 && python manage.py runserver 0.0.0.0:8000" ]
#    volumes:
#      - .:/app
#    ports:
#      - "8000:8000"
#    depends_on:
#      - mysql

volumes:
  mysql_data:
