# Generated by Django 5.0.6 on 2024-06-05 08:34

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('feedback', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.Review.user_directory_path)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
